### ISSUE TITLE
v1.searchSLO SearchSLOResponse does not match actual API response

### ISSUE THREAD

**Issue by mscharp** [DataDog/datadog-api-client-typescript#855]
**Describe the bug**
 - Cannot use searchSLO without enabling "unstableOperations" (which doesn't seem to be documented anywhere).
 - The typescript types and parsing of the API response does not match what the actual API returns.  For example, the api response is "data.attributes.slos" whereas the SearchSLOResponse has "data.attributes.slo".  
 - SearchSLOResponse "data.attributes.unparsedObject" is undefined.
 - etc

Label the issue properly.

This api is unusable as a result of this bug.

**To Reproduce**

Use the typescript project to search for an SLO and use the response.

**Expected behavior**
SearchSLOResponse should have all properties populated and match the actual response from the API.

**Screenshots**
![Screen Shot 2022-09-27 at 10 47 36 AM](https://user-images.githubusercontent.com/1426929/192587505-e9535c1a-3d5e-4517-b5d2-056dfe738185.png)

**Environment and Versions (please complete the following information):**
- "typescript": "^4.8.3"
- "@datadog/datadog-api-client": "^1.3.0"

**Comment by therve** [comment]
Hi,

The unstable status is documented, you can see the examples with the call here: https://docs.datadoghq.com/api/latest/service-level-objectives/?code-lang=typescript#search-for-slos or here: https://github.com/DataDog/datadog-api-client-typescript/blob/master/examples/v1/service-level-objectives/SearchSLO.ts.

The response body is completely inaccurate though. This should be fixed by #856 , thanks for your patience.

**Comment by mscharp** [comment]
Thanks!  Do you know when a new release will be made available?
